remote_theme: pmarsceill/just-the-docs

# Optional customization
title: AWS CDK with TypeScript & GitLab CI/CD Workshop
description: A 3-day workshop building a document processing pipeline
color_scheme: light # or dark

# Make all pages appear in navigation
# nav_sort: case_insensitive # default is case_sensitive